import type { RentalItem, StockTransaction, Chamber, GatePass, User, Vendor, Client, Invoice, OutwardEntry, DeliveryOrder, GoodsReceiptNote } from '@/lib/types';

export const users: User[] = [
  { id: 'user_01', name: 'Alex', email: 'alex@example.com', role: 'Admin' },
  { id: 'user_02', name: 'Maria', email: 'maria@example.com', role: 'Storekeeper' },
  { id: 'user_03', name: 'Chen', email: 'chen@example.com', role: 'Gatekeeper' }
];

export const vendors: Vendor[] = [
    { id: 'vendor_01', name: 'Global Foods Inc.' },
    { id: 'vendor_02', name: 'Fresh Produce Co.' },
    { id: 'vendor_03', name: 'Link Logistics' }
];

export const clients: Client[] = [
    { id: 'cust_01', name: 'JK TRADING COMPANY', phone: '9876543210', address: 'Market Yard, Bangalore', billingCycle: 'monthly', rentAmount: 50000, pendingPayment: 10000 },
    { id: 'cust_02', name: 'Prestige Catering', phone: '9876543211', address: '123 Food Street, Bangalore', billingCycle: 'monthly', rentAmount: 25000, pendingPayment: 0 },
    { id: 'cust_03', name: 'SHEETAL ENTERPRISES', phone: '9876543212', address: 'Indiranagar, Bangalore', billingCycle: 'monthly', rentAmount: 35000, pendingPayment: 5000 },
];

export const rentalItems: RentalItem[] = [
  // SHEETAL ENTERPRISES ITEMS
  {
    id: 'item_sheetal_07362',
    inwardNumber: '07362',
    name: 'WHIIP CREAM',
    brand: 'TESTY',
    batchNumber: '',
    category: 'Dairy',
    description: 'Cold storage',
    rentalRate: 1.5,
    rentalCycles: ['monthly'],
    inwardQuantity: 5,
    outwardQuantity: 0,
    quantityAvailable: 5,
    unit: 'boxes',
    inwardWeight: 60.00,
    outwardWeight: 0.00,
    balanceWeight: 60.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-07-07'),
    temperatureRange: '-18°C',
    vendorId: 'vendor_03',
    clientId: 'cust_03',
    chamberId: 'chamber_01',
    driverName: 'UNKNOWN',
    vehicleNumber: 'UNKNOWN',
    images: [],
    condition: 'New'
  },
  {
    id: 'item_sheetal_07994',
    inwardNumber: '07994',
    name: 'WHIIP CREAM',
    brand: 'PEARL',
    batchNumber: '',
    category: 'Dairy',
    description: 'Cold storage',
    rentalRate: 1.5,
    rentalCycles: ['monthly'],
    inwardQuantity: 70,
    outwardQuantity: 67,
    quantityAvailable: 3,
    unit: 'boxes',
    inwardWeight: 840.00,
    outwardWeight: 804.00,
    balanceWeight: 36.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-11-23'),
    temperatureRange: '-18°C',
    vendorId: 'vendor_03',
    clientId: 'cust_03',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'item_sheetal_08152',
    inwardNumber: '08152',
    name: 'WHIIP CREAM',
    brand: 'PEARL',
    batchNumber: '',
    category: 'Dairy',
    description: 'Cold storage',
    rentalRate: 1.5,
    rentalCycles: ['monthly'],
    inwardQuantity: 30,
    outwardQuantity: 0,
    quantityAvailable: 30,
    unit: 'boxes',
    inwardWeight: 360.00,
    outwardWeight: 0.00,
    balanceWeight: 360.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-12-26'),
    temperatureRange: '-18°C',
    vendorId: 'vendor_03',
    clientId: 'cust_03',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'item_sheetal_08213',
    inwardNumber: '08213',
    name: 'WHIIP CREAM',
    brand: 'DECOR',
    batchNumber: 'BATCH-A1',
    category: 'Dairy',
    description: 'Cold storage',
    rentalRate: 1.5,
    rentalCycles: ['monthly'],
    inwardQuantity: 100,
    outwardQuantity: 100,
    quantityAvailable: 0,
    unit: 'boxes',
    inwardWeight: 1200.00,
    outwardWeight: 1200.00,
    balanceWeight: 0.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2026-01-09'),
    temperatureRange: '-18°C',
    vendorId: 'vendor_03',
    clientId: 'cust_03',
    chamberId: 'chamber_01',
    driverName: 'BIRAPPA',
    vehicleNumber: 'MH12 DT2119',
    images: [],
    condition: 'New'
  },
  {
    id: 'item_sheetal_08213_choco',
    inwardNumber: '08213',
    name: 'CHOCO TRAPHAL',
    brand: 'DECOR',
    batchNumber: '',
    category: 'Dairy',
    description: 'Cold storage',
    rentalRate: 1.5,
    rentalCycles: ['monthly'],
    inwardQuantity: 20,
    outwardQuantity: 0,
    quantityAvailable: 20,
    unit: 'boxes',
    inwardWeight: 240.00,
    outwardWeight: 0.00,
    balanceWeight: 240.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2026-01-09'),
    temperatureRange: '-18°C',
    vendorId: 'vendor_03',
    clientId: 'cust_03',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },

  // JK TRADING COMPANY ITEMS (From Chambers Report Image)
  {
    id: 'jk_06840',
    inwardNumber: '06840',
    name: 'JWARI',
    brand: 'MANIK',
    batchNumber: 'JKT110',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 110,
    outwardQuantity: 9,
    quantityAvailable: 101,
    unit: 'bags',
    inwardWeight: 3300.00,
    outwardWeight: 270.00,
    balanceWeight: 3030.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-09'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06856',
    inwardNumber: '06856',
    name: 'JWARI',
    brand: 'MAHARAJA',
    batchNumber: 'JKT114',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 114,
    outwardQuantity: 0,
    quantityAvailable: 114,
    unit: 'bags',
    inwardWeight: 3420.00,
    outwardWeight: 0.00,
    balanceWeight: 3420.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-12'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06863',
    inwardNumber: '06863',
    name: 'JWARI',
    brand: 'RAJHANS',
    batchNumber: 'JKT90',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 90,
    outwardQuantity: 38,
    quantityAvailable: 52,
    unit: 'bags',
    inwardWeight: 2700.00,
    outwardWeight: 1140.00,
    balanceWeight: 1560.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-13'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06872_1',
    inwardNumber: '06872',
    name: 'JWARI',
    brand: 'LAYBHARI',
    batchNumber: 'JKT120',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 120,
    outwardQuantity: 0,
    quantityAvailable: 120,
    unit: 'bags',
    inwardWeight: 3600.00,
    outwardWeight: 0.00,
    balanceWeight: 3600.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-15'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06872_2',
    inwardNumber: '06872',
    name: 'JWARI',
    brand: 'RAJHANS',
    batchNumber: 'JKT101',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 101,
    outwardQuantity: 0,
    quantityAvailable: 101,
    unit: 'bags',
    inwardWeight: 3030.00,
    outwardWeight: 0.00,
    balanceWeight: 3030.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-15'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06872_3',
    inwardNumber: '06872',
    name: 'JWARI',
    brand: 'MAHARAJA',
    batchNumber: 'JKT159',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 159,
    outwardQuantity: 45,
    quantityAvailable: 114,
    unit: 'bags',
    inwardWeight: 4770.00,
    outwardWeight: 1350.00,
    balanceWeight: 3420.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-15'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06881_1',
    inwardNumber: '06881',
    name: 'JWARI',
    brand: 'RAJHANS',
    batchNumber: 'JKT100',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 100,
    outwardQuantity: 0,
    quantityAvailable: 100,
    unit: 'bags',
    inwardWeight: 3000.00,
    outwardWeight: 0.00,
    balanceWeight: 3000.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-16'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_08',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06881_2',
    inwardNumber: '06881',
    name: 'JWARI',
    brand: 'LAYBHARI',
    batchNumber: 'JKT151',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 151,
    outwardQuantity: 0,
    quantityAvailable: 151,
    unit: 'bags',
    inwardWeight: 4530.00,
    outwardWeight: 0.00,
    balanceWeight: 4530.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-16'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_08',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06888',
    inwardNumber: '06888',
    name: 'JWARI',
    brand: 'KOHINOOR',
    batchNumber: 'JKT90',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 90,
    outwardQuantity: 0,
    quantityAvailable: 90,
    unit: 'bags',
    inwardWeight: 2700.00,
    outwardWeight: 0.00,
    balanceWeight: 2700.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-18'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06889_1',
    inwardNumber: '06889',
    name: 'JWARI',
    brand: 'LAL OM',
    batchNumber: 'JKT94',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 94,
    outwardQuantity: 0,
    quantityAvailable: 94,
    unit: 'bags',
    inwardWeight: 2820.00,
    outwardWeight: 0.00,
    balanceWeight: 2820.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-18'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06889_2',
    inwardNumber: '06889',
    name: 'JWARI',
    brand: 'SUDARSHAN',
    batchNumber: 'JKT101',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 101,
    outwardQuantity: 0,
    quantityAvailable: 101,
    unit: 'bags',
    inwardWeight: 3030.00,
    outwardWeight: 0.00,
    balanceWeight: 3030.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-18'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06932_1',
    inwardNumber: '06932',
    name: 'JWARI',
    brand: 'RAJHANS',
    batchNumber: 'JKT59',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 59,
    outwardQuantity: 17,
    quantityAvailable: 42,
    unit: 'bags',
    inwardWeight: 1770.00,
    outwardWeight: 510.00,
    balanceWeight: 1260.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-25'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06932_2',
    inwardNumber: '06932',
    name: 'JWARI',
    brand: 'NILA OM',
    batchNumber: 'JKT119',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 119,
    outwardQuantity: 0,
    quantityAvailable: 119,
    unit: 'bags',
    inwardWeight: 3570.00,
    outwardWeight: 0.00,
    balanceWeight: 3570.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-04-25'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_06989',
    inwardNumber: '06989',
    name: 'JWARI',
    brand: 'HIRVA',
    batchNumber: 'JKT90',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 90,
    outwardQuantity: 0,
    quantityAvailable: 90,
    unit: 'bags',
    inwardWeight: 2700.00,
    outwardWeight: 0.00,
    balanceWeight: 2700.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-01'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_3B',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07052',
    inwardNumber: '07052',
    name: 'JWARI',
    brand: 'VIP',
    batchNumber: 'JKT135',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 135,
    outwardQuantity: 0,
    quantityAvailable: 135,
    unit: 'bags',
    inwardWeight: 4050.00,
    outwardWeight: 0.00,
    balanceWeight: 4050.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-11'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07085',
    inwardNumber: '07085',
    name: 'JWARI',
    brand: 'RAJHANS',
    batchNumber: 'JKT98',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 98,
    outwardQuantity: 0,
    quantityAvailable: 98,
    unit: 'bags',
    inwardWeight: 2940.00,
    outwardWeight: 0.00,
    balanceWeight: 2940.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-17'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07102',
    inwardNumber: '07102',
    name: 'JWARI',
    brand: 'KISAN',
    batchNumber: 'JKT70',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 70,
    outwardQuantity: 0,
    quantityAvailable: 70,
    unit: 'bags',
    inwardWeight: 2100.00,
    outwardWeight: 0.00,
    balanceWeight: 2100.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-20'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07106',
    inwardNumber: '07106',
    name: 'WHEAT',
    brand: 'KHAPLI',
    batchNumber: 'JKT100',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 100,
    outwardQuantity: 80,
    quantityAvailable: 20,
    unit: 'bags',
    inwardWeight: 3000.00,
    outwardWeight: 2400.00,
    balanceWeight: 600.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-21'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07110_1',
    inwardNumber: '07110',
    name: 'JWARI',
    brand: 'RAJHANS',
    batchNumber: 'JKT95',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 95,
    outwardQuantity: 1,
    quantityAvailable: 94,
    unit: 'bags',
    inwardWeight: 2850.00,
    outwardWeight: 30.00,
    balanceWeight: 2820.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-23'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07110_2',
    inwardNumber: '07110',
    name: 'JWARI',
    brand: 'DUBBLE',
    batchNumber: 'JKT157',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 157,
    outwardQuantity: 0,
    quantityAvailable: 157,
    unit: 'bags',
    inwardWeight: 4710.00,
    outwardWeight: 0.00,
    balanceWeight: 4710.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-23'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07120_1',
    inwardNumber: '07120',
    name: 'JWARI',
    brand: 'LAL KISAN',
    batchNumber: 'JKT167',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 167,
    outwardQuantity: 0,
    quantityAvailable: 167,
    unit: 'bags',
    inwardWeight: 5010.00,
    outwardWeight: 0.00,
    balanceWeight: 5010.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-23'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07120_2',
    inwardNumber: '07120',
    name: 'JWARI',
    brand: 'LAL OM',
    batchNumber: 'JKT89',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 89,
    outwardQuantity: 0,
    quantityAvailable: 89,
    unit: 'bags',
    inwardWeight: 2670.00,
    outwardWeight: 0.00,
    balanceWeight: 2670.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-05-23'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07160',
    inwardNumber: '07160',
    name: 'JWARI',
    brand: 'LAL OM',
    batchNumber: 'JKT50',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 50,
    outwardQuantity: 0,
    quantityAvailable: 50,
    unit: 'bags',
    inwardWeight: 1500.00,
    outwardWeight: 0.00,
    balanceWeight: 1500.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-06-01'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  },
  {
    id: 'jk_07200',
    inwardNumber: '07200',
    name: 'JWARI',
    brand: '5 STAR',
    batchNumber: 'JKT177',
    category: 'Grains',
    description: 'Storage Item',
    rentalRate: 0.45,
    rentalCycles: ['monthly'],
    inwardQuantity: 177,
    outwardQuantity: 0,
    quantityAvailable: 177,
    unit: 'bags',
    inwardWeight: 5310.00,
    outwardWeight: 0.00,
    balanceWeight: 5310.00,
    expiryDate: new Date('2026-12-31'),
    storageDate: new Date('2025-06-04'),
    temperatureRange: 'Ambient',
    vendorId: 'vendor_01',
    clientId: 'cust_01',
    chamberId: 'chamber_01',
    images: [],
    condition: 'New'
  }
];

export const outwardEntries: OutwardEntry[] = [
  // SHEETAL ENTERPRISES ENTRIES
  {
    id: 'out_sheetal_01',
    outwardNumber: '24421',
    outwardDate: new Date('2026-01-02'),
    clientId: 'cust_03',
    inwardNumber: '08152',
    itemName: 'WHIIP CREAM',
    brand: 'PEARL',
    quantity: 20,
    weight: 240.00,
    driverName: 'AKSHAY',
    vehicleNumber: 'MH12TN5281'
  },
  {
    id: 'out_sheetal_02',
    outwardNumber: '24638',
    outwardDate: new Date('2026-01-14'),
    clientId: 'cust_03',
    inwardNumber: '07994',
    itemName: 'WHIIP CREAM',
    brand: 'PEARL',
    quantity: 3,
    weight: 36.00,
    driverName: 'AKSHAY',
    vehicleNumber: 'MH12TN5281'
  },
  // JK TRADING COMPANY ENTRIES
  {
    id: 'out_jk_01',
    outwardNumber: '24401',
    outwardDate: new Date('2025-12-01'),
    clientId: 'cust_01',
    inwardNumber: '06840',
    itemName: 'JWARI',
    brand: 'MANIK',
    quantity: 9,
    weight: 270.00,
    driverName: 'CHORGHE',
    vehicleNumber: 'MH12UM4494'
  },
  {
    id: 'out_jk_02',
    outwardNumber: '24402',
    outwardDate: new Date('2025-12-05'),
    clientId: 'cust_01',
    inwardNumber: '06863',
    itemName: 'JWARI',
    brand: 'RAJHANS',
    quantity: 38,
    weight: 1140.00,
    driverName: 'CHORGHE',
    vehicleNumber: 'MH12UM4494'
  },
  {
    id: 'out_jk_03',
    outwardNumber: '24403',
    outwardDate: new Date('2025-12-10'),
    clientId: 'cust_01',
    inwardNumber: '06872',
    itemName: 'JWARI',
    brand: 'MAHARAJA',
    quantity: 45,
    weight: 1350.00,
    driverName: 'CHORGHE',
    vehicleNumber: 'MH12UM4494'
  }
];

export const deliveryOrders: DeliveryOrder[] = [
  {
    id: 'do_24421',
    orderNumber: '24421',
    date: new Date('2026-01-02'),
    clientId: 'cust_03',
    address: 'PUNE',
    remark: '',
    driverName: 'AKSHAY',
    vehicleNumber: 'MH12 TN5281',
    gatePassNumber: '01787',
    items: [
      {
        srNo: 1,
        itemName: 'WHIIP CREAM',
        inwardNumber: '08152',
        brand: 'PEARL',
        quantity: 20,
        unit: 'BOX',
        weight: 240.00,
        balanceQty: 10,
        balanceWeight: 120.00
      }
    ]
  },
  {
    id: 'do_24638',
    orderNumber: '24638',
    date: new Date('2026-01-14'),
    clientId: 'cust_03',
    address: 'PUNE',
    remark: '',
    driverName: 'AKSHAY',
    vehicleNumber: 'MH12 TN5281',
    gatePassNumber: '01946',
    items: [
      {
        srNo: 1,
        itemName: 'WHIIP CREAM',
        inwardNumber: '07994',
        brand: 'PEARL',
        quantity: 3,
        unit: 'BOX',
        weight: 36.00,
        balanceQty: 0,
        balanceWeight: 0
      }
    ]
  }
];

export const goodsReceiptNotes: GoodsReceiptNote[] = [
  {
    id: 'grn_01',
    grnNumber: 'GRN-08213',
    inwardNumber: '08213',
    date: new Date('2026-01-09'),
    clientId: 'cust_03',
    address: 'PUNE',
    remark: '',
    driverName: 'BIRAPPA',
    vehicleNumber: 'MH12 DT2119',
    gatePassNumber: '08038',
    items: [
      {
        srNo: 1,
        itemName: 'WHIIP CREAM',
        brand: 'DECOR',
        batchNumber: '',
        unit: 'BOX',
        weightPerQty: 12,
        quantity: 100,
        weight: 1200.00
      }
    ]
  }
];

export const chambers: Chamber[] = [
  {
    id: 'chamber_01',
    name: 'FREEZER-1',
    temperature: '-18°C',
    isActive: true,
    dailyRentRate: 800,
    products: [
        { id: 'item_sheetal_01', name: 'WHIIP CREAM', quantityAvailable: 100, unit: 'boxes' },
    ],
    boxDimensions: { length: 800, width: 600, height: 300 }
  },
  {
    id: 'chamber_08',
    name: 'FREEZER-8',
    temperature: '-18°C',
    isActive: true,
    dailyRentRate: 800,
    products: [],
    boxDimensions: { length: 800, width: 600, height: 300 }
  },
  {
    id: 'chamber_3B',
    name: 'FREEZER-3B',
    temperature: '-18°C',
    isActive: true,
    dailyRentRate: 800,
    products: [],
    boxDimensions: { length: 800, width: 600, height: 300 }
  }
];

export const gatePasses: GatePass[] = [];

export const invoices: Invoice[] = [
    {
        id: 'inv_02163',
        invoiceNumber: '02163',
        clientId: 'cust_03',
        date: new Date('2026-02-05'),
        dueDate: new Date('2026-02-20'),
        items: [
            { itemId: 'item_sheetal_07362', name: 'WHIIP CREAM (DECOR)', quantity: 5, rate: 1500, amount: 90 },
            { itemId: 'item_sheetal_07994', name: 'WHIIP CREAM (PEARL)', quantity: 3, rate: 1500, amount: 54 },
            { itemId: 'item_sheetal_08152', name: 'WHIIP CREAM (PEARL)', quantity: 30, rate: 1500, amount: 540 },
            { itemId: 'item_sheetal_08213', name: 'WHIIP CREAM (DECOR)', quantity: 100, rate: 1500, amount: 1800 },
            { itemId: 'item_sheetal_08213_choco', name: 'CHOCO TRAPHAL (DECOR)', quantity: 20, rate: 1500, amount: 360 },
        ],
        subtotal: 3576.56, // Taxable amount
        tax: 643.78, // 321.89 + 321.89
        total: 4220,
        paidAmount: 0,
        balance: 4220,
        status: 'Pending'
    },
    {
        id: 'inv_jk_02151',
        invoiceNumber: '02151',
        clientId: 'cust_01',
        date: new Date('2026-02-05'),
        dueDate: new Date('2026-02-20'),
        items: [
            { itemId: 'jk_06840', name: 'JWARI (MANIK)', quantity: 101, rate: 0.45, amount: 1363.50 },
            { itemId: 'jk_06856', name: 'JWARI (MANIK)', quantity: 114, rate: 0.45, amount: 1539.00 },
            { itemId: 'jk_06863', name: 'JWARI (MANIK)', quantity: 52, rate: 0.45, amount: 702.00 },
            { itemId: 'jk_07106', name: 'WHEAT (LOCAL)', quantity: 20, rate: 0.45, amount: 270.00 },
        ],
        subtotal: 3874.50,
        tax: 697.41,
        total: 4571.91,
        paidAmount: 0,
        balance: 4571.91,
        status: 'Pending'
    }
];

export const transactions: StockTransaction[] = [];
